version: "3.8"

services:
  api:
    build: .
    ports: 
      - 8001:8000
    env_file:
     - ./.env
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
     - ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PSW}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: