"""add phone number

Revision ID: 583b636018f8
Revises: 0720a52d72e2
Create Date: 2022-01-01 18:27:52.026333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583b636018f8'
down_revision = '0720a52d72e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
